# -*- coding: utf-8 -*-
"""YouTube Video Q&A Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enUUYWImSZwc2QIm7TEwjQFp14LC2Zsf

## Install libraries
"""

!pip install -q youtube-transcript-api langchain-community \
faiss-cpu tiktoken python-dotenv  langchain-text-splitters transformers accelerate torch langchain-huggingface

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from transformers import pipeline
from langchain_huggingface import HuggingFacePipeline, HuggingFaceEmbeddings

"""## Step 1a - Indexing (Document Ingestion)"""

# only the ID, not full URL
# video_id = "Gfr50f6ZBvo"
video_id = 'kovF86_WqmQ'
try:

    ytt_api = YouTubeTranscriptApi()

    # If you don’t care which language, this returns the “best” one
    transcript_list = ytt_api.fetch(video_id, languages=["en"])

    # Flatten it to plain text
    transcript = " ".join(chunk.text for chunk in transcript_list)

    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")

"""## Step 1b - Indexing (Text Splitting)"""

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = splitter.create_documents([transcript])

"""## Step 1c & 1d - Indexing (Embedding Generation and Storing in Vector Store)"""

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en-v1.5"
)
vector_store = FAISS.from_documents(chunks, embeddings)

"""## Step 2 - Retrieval"""

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 2})

"""## Step 3 - Augmentation"""

# pipe = pipeline(
#     "text-generation",
#     model="microsoft/Phi-3-mini-4k-instruct",
#     device_map="auto"
# )
# pipe = pipeline(
#     "text-generation",
#     model="google/gemma-2-2b-it",
#     device_map="auto"
# )
pipe = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    max_new_tokens=64,
    device_map="auto"
)

llm = HuggingFacePipeline(pipeline=pipe)

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

"""## Building a Chain"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_docs):
  context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
  return context_text

parallel_chain = RunnableParallel({
    'context': retriever | RunnableLambda(format_docs),
    'question': RunnablePassthrough()
})

parser = StrOutputParser()

main_chain = parallel_chain | prompt | llm | parser

main_chain.invoke('Can you summarize the video')

